name = input("Введи свое имя - ")
print("Привет, " + name + "!")
number = int(input("Введи целое число - "))
print(number)
string = input("Введи слово - ")
print(string)
number_f = float(input("Введи вещественное число - "))
print(number_f)
